import Foundation

@main
struct InjectHeirloomSecretsTool {
    static func main() {
        let args = CommandLine.arguments
        guard args.count == 3 else {
            fail("usage: InjectHeirloomSecretsTool <config.json> <output.swift>")
        }
        let configPath = args[1]
        let outputPath = args[2]

        guard FileManager.default.fileExists(atPath: configPath) else {
            fail(
                """
                HeirloomSecrets config missing at \(configPath). Create a \
                HeirloomSecrets.json at the target source root.
                """
            )
        }

        let configData: Data
        do {
            configData = try Data(contentsOf: URL(fileURLWithPath: configPath))
        } catch {
            fail("failed to read \(configPath): \(error)")
        }

        let config: Config
        do {
            config = try JSONDecoder().decode(Config.self, from: configData)
        } catch {
            fail("failed to parse \(configPath): \(error)")
        }

        let properties = config.secrets
            .sorted { $0.key < $1.key }
            .map { name, secret in
                let value = resolve(secret: secret, property: "\(config.enumName).\(name)")
                return "    static let \(name): String = \(encodeSwiftLiteral(value))"
            }

        let output = """
            // Auto-generated by HeirloomSecrets. Do not edit.
            // Regenerated on every build from environment variables.

            nonisolated enum \(config.enumName) {
            \(properties.joined(separator: "\n"))
            }

            """

        writeAtomic(output, to: outputPath)
    }

    private static func resolve(secret: SecretConfig, property: String) -> String {
        if let raw = ProcessInfo.processInfo.environment[secret.envVar] {
            return raw
        }
        if secret.allowMissing == true {
            warn("environment variable \(secret.envVar) is unset; emitting empty string for \(property)")
            return ""
        }
        fail(
            """
            environment variable \(secret.envVar) must be set to generate \(property). \
            Set it in your shell, ~/.zshenv (for Xcode.app), or your CI environment.
            """
        )
    }

    private static func encodeSwiftLiteral(_ value: String) -> String {
        let encoded = try? JSONEncoder().encode(value)
        return encoded.flatMap { String(data: $0, encoding: .utf8) } ?? "\"\""
    }

    private static func writeAtomic(_ contents: String, to path: String) {
        do {
            try contents.write(toFile: path, atomically: true, encoding: .utf8)
        } catch {
            fail("failed to write \(path): \(error)")
        }
    }
}

private struct SecretConfig: Decodable {
    let envVar: String
    let allowMissing: Bool?
}

private struct Config: Decodable {
    let enumName: String
    let secrets: [String: SecretConfig]
}

private func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data("error: \(message)\n".utf8))
    exit(1)
}

private func warn(_ message: String) {
    FileHandle.standardError.write(Data("warning: \(message)\n".utf8))
}
