import Foundation
import Testing
import TightlipCore

@Suite("renderSecretsEnum")
struct RenderSecretsEnumTests {
    @Test func rendersSingleSecretAsObfuscatedDecodeCall() {
        let out = renderSecretsEnum([(name: "revenueCatAPIKey", value: "abc")])
        #expect(out.contains("static let revenueCatAPIKey: Swift.String = Self.decode(\""))
    }

    @Test func sortsSecretsAlphabetically() {
        let out = renderSecretsEnum([
            (name: "zeta", value: "z"),
            (name: "alpha", value: "a"),
            (name: "mu", value: "m"),
        ])
        guard
            let alphaIdx = out.range(of: "static let alpha:"),
            let muIdx = out.range(of: "static let mu:"),
            let zetaIdx = out.range(of: "static let zeta:")
        else {
            Issue.record("expected all three property declarations")
            return
        }
        #expect(alphaIdx.lowerBound < muIdx.lowerBound)
        #expect(muIdx.lowerBound < zetaIdx.lowerBound)
    }

    @Test func rendersEmptyEnumWhenNoSecrets() {
        let out = renderSecretsEnum([])
        #expect(!out.contains("Self.decode("))
        #expect(out.contains("private static let salt:"))
        #expect(out.contains("private static func decode("))
    }

    @Test func headerCommentsArePresent() {
        let out = renderSecretsEnum([(name: "k", value: "v")])
        #expect(out.hasPrefix("// Auto-generated by Tightlip. Do not edit.\n"))
        #expect(
            out.contains(
                "// Regenerated from environment variables when Secrets.yml or the env file changes."
            ))
    }

    @Test func importsFoundationForData() {
        let out = renderSecretsEnum([(name: "k", value: "v")])
        #expect(out.contains("import Foundation"))
    }

    @Test func includesEnvironmentAnnotationWhenProvided() {
        let out = renderSecretsEnum([(name: "k", value: "v")], environment: "staging")
        #expect(out.contains("// Environment: staging"))
    }

    @Test func omitsEnvironmentAnnotationWhenNil() {
        let out = renderSecretsEnum([(name: "k", value: "v")])
        #expect(!out.contains("// Environment:"))
    }

    @Test func saltArrayHas32Bytes() {
        let out = renderSecretsEnum([(name: "k", value: "v")])
        guard let saltLine = out.split(separator: "\n").first(where: { $0.contains("private static let salt:") }) else {
            Issue.record("expected salt line")
            return
        }
        let hexCount = saltLine.components(separatedBy: "0x").count - 1
        #expect(hexCount == 32)
    }

    @Test func decodeShimQualifiesLibrarySymbols() {
        // A consumer type named `Data` or `UTF8` in the same module must not capture
        // the shim's references; every library symbol is spelled module-qualified.
        let out = renderSecretsEnum([(name: "k", value: "v")])
        #expect(out.contains("private static func decode(_ encoded: Swift.String) -> Swift.String"))
        #expect(out.contains("Foundation.Data(base64Encoded: encoded)"))
        #expect(out.contains("Swift.String(decoding: bytes, as: Swift.UTF8.self)"))
        #expect(out.contains("Swift.fatalError("))
    }

    @Test func decodeTrapsInsteadOfReturningEmptyString() {
        // A base64 failure can only mean a corrupted generated file. Returning
        // "" would hand the app a silently-empty API key at runtime.
        let out = renderSecretsEnum([(name: "k", value: "v")])
        #expect(out.contains("fatalError("))
        #expect(!out.contains("return \"\""))
    }
}

@Suite("renderSecretsEnum — access level")
struct RenderSecretsEnumAccessTests {
    static let secrets: [(name: String, value: String)] = [(name: "alpha", value: "a"), (name: "beta", value: "b")]

    @Test func internalIsByteIdenticalToTheDefault() {
        let explicit = renderSecretsEnum(Self.secrets, environment: "staging", access: .internal)
        #expect(explicit == renderSecretsEnum(Self.secrets, environment: "staging"))
        #expect(explicit.contains("\nnonisolated enum Secrets {\n"))
        #expect(explicit.contains("\n    static let alpha: Swift.String"))
        #expect(!explicit.contains("internal"))
    }

    @Test(arguments: [AccessLevel.package, .public])
    func keywordLeadsTheEnumAndEveryProperty(access: AccessLevel) {
        let out = renderSecretsEnum(Self.secrets, access: access)
        let keyword = access.rawValue
        #expect(out.contains("\n\(keyword) nonisolated enum Secrets {\n"))
        #expect(out.contains("\n    \(keyword) static let alpha: Swift.String = Self.decode(\""))
        #expect(out.contains("\n    \(keyword) static let beta: Swift.String = Self.decode(\""))
        #expect(out.contains("\n    private static let salt: [Swift.UInt8]"))
        #expect(out.contains("\n    private static func decode(_ encoded: Swift.String)"))
    }

    @Test(arguments: [AccessLevel.package, .public])
    func onlyTheKeywordDiffersFromInternal(access: AccessLevel) {
        // Same salt and payloads: the access level is not an input to obfuscation.
        let widened = renderSecretsEnum(Self.secrets, access: access)
        let stripped = widened.replacingOccurrences(of: "\(access.rawValue) ", with: "")
        #expect(stripped == renderSecretsEnum(Self.secrets))
    }
}
