import HeirloomSecretsCore
import Testing

@Suite("renderSecretsEnum")
struct RenderSecretsEnumTests {
    @Test func rendersSingleSecret() {
        let out = renderSecretsEnum([(name: "revenueCatAPIKey", value: "abc")])
        let expected = """
            // Auto-generated by HeirloomSecrets. Do not edit.
            // Regenerated on every build from environment variables.

            nonisolated enum Secrets {
                static let revenueCatAPIKey: String = "abc"
            }

            """
        #expect(out == expected)
    }

    @Test func sortsSecretsAlphabetically() {
        let out = renderSecretsEnum([
            (name: "zeta", value: "z"),
            (name: "alpha", value: "a"),
            (name: "mu", value: "m"),
        ])
        let body = """
                static let alpha: String = "a"
                static let mu: String = "m"
                static let zeta: String = "z"
            """
        #expect(out.contains(body))
    }

    @Test func escapesValuesViaSwiftLiteralEncoder() {
        let out = renderSecretsEnum([(name: "key", value: "a\"b\\c")])
        #expect(out.contains(#"static let key: String = "a\"b\\c""#))
    }

    @Test func rendersEmptyEnumBodyForNoSecrets() {
        let out = renderSecretsEnum([])
        let expected = """
            // Auto-generated by HeirloomSecrets. Do not edit.
            // Regenerated on every build from environment variables.

            nonisolated enum Secrets {

            }

            """
        #expect(out == expected)
    }

    @Test func headerCommentsArePresent() {
        let out = renderSecretsEnum([(name: "k", value: "v")])
        #expect(out.hasPrefix("// Auto-generated by HeirloomSecrets. Do not edit.\n"))
        #expect(out.contains("// Regenerated on every build from environment variables."))
    }

    @Test func includesEnvironmentAnnotationWhenProvided() {
        let out = renderSecretsEnum([(name: "k", value: "v")], environment: "staging")
        #expect(out.contains("// Environment: staging"))
    }

    @Test func omitsEnvironmentAnnotationWhenNil() {
        let out = renderSecretsEnum([(name: "k", value: "v")])
        #expect(!out.contains("// Environment:"))
    }
}
