import HeirloomSecretsCore
import Testing

@Suite("renderSecretsEnum")
struct RenderSecretsEnumTests {
    @Test func rendersSingleSecretAsObfuscatedDecodeCall() {
        let out = renderSecretsEnum([(name: "revenueCatAPIKey", value: "abc")])
        #expect(out.contains("static let revenueCatAPIKey: String = Self.decode(\""))
    }

    @Test func sortsSecretsAlphabetically() {
        let out = renderSecretsEnum([
            (name: "zeta", value: "z"),
            (name: "alpha", value: "a"),
            (name: "mu", value: "m"),
        ])
        guard
            let alphaIdx = out.range(of: "static let alpha:"),
            let muIdx = out.range(of: "static let mu:"),
            let zetaIdx = out.range(of: "static let zeta:")
        else {
            Issue.record("expected all three property declarations")
            return
        }
        #expect(alphaIdx.lowerBound < muIdx.lowerBound)
        #expect(muIdx.lowerBound < zetaIdx.lowerBound)
    }

    @Test func rendersEmptyEnumWhenNoSecrets() {
        let out = renderSecretsEnum([])
        #expect(!out.contains("Self.decode("))
        #expect(out.contains("private static let salt:"))
        #expect(out.contains("private static func decode("))
    }

    @Test func headerCommentsArePresent() {
        let out = renderSecretsEnum([(name: "k", value: "v")])
        #expect(out.hasPrefix("// Auto-generated by HeirloomSecrets. Do not edit.\n"))
        #expect(out.contains("// Regenerated on every build from environment variables."))
    }

    @Test func importsFoundationForData() {
        let out = renderSecretsEnum([(name: "k", value: "v")])
        #expect(out.contains("import Foundation"))
    }

    @Test func includesEnvironmentAnnotationWhenProvided() {
        let out = renderSecretsEnum([(name: "k", value: "v")], environment: "staging")
        #expect(out.contains("// Environment: staging"))
    }

    @Test func omitsEnvironmentAnnotationWhenNil() {
        let out = renderSecretsEnum([(name: "k", value: "v")])
        #expect(!out.contains("// Environment:"))
    }

    @Test func saltArrayHas32Bytes() {
        let out = renderSecretsEnum([(name: "k", value: "v")])
        guard let saltLine = out.split(separator: "\n").first(where: { $0.contains("private static let salt:") }) else {
            Issue.record("expected salt line")
            return
        }
        let hexCount = saltLine.components(separatedBy: "0x").count - 1
        #expect(hexCount == 32)
    }

    @Test func decodeFunctionShape() {
        let out = renderSecretsEnum([(name: "k", value: "v")])
        #expect(out.contains("private static func decode(_ encoded: String) -> String"))
        #expect(out.contains("Data(base64Encoded: encoded)"))
        #expect(out.contains("bytes[i] ^= salt[i % salt.count]"))
    }
}
